# -*- coding: utf-8 -*-
"""TrueValue 3.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cs63wQSTFOLGfY3G06mwf_1MVWCWIKIV
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

st.set_page_config(page_title="Quant Pro Valuation", layout="wide")

st.title("📊 Advanced Quantitative Valuation Dashboard")

# Sidebar
ticker_symbol = st.sidebar.text_input("Enter Ticker", "AAPL")
lookback_years = st.sidebar.slider("Historical Lookback (Years)", 2, 10, 5)

@st.cache_data
def get_data(ticker, years):
    tk = yf.Ticker(ticker)
    hist = tk.history(period=f"{years}y")
    info = tk.info
    eps = info.get('trailingEps')
    if not eps or hist.empty:
        return None, None
    hist['Proxy_PE'] = hist['Close'] / eps
    return hist, info

data, info = get_data(ticker_symbol, lookback_years)

if data is not None:
    current_pe = info.get('trailingPE', data['Proxy_PE'].iloc[-1])
    hist_pe = data['Proxy_PE'].dropna()

    # --- METRICS SECTION ---
    c1, c2, c3 = st.columns(3)
    c1.metric("Current P/E", f"{current_pe:.2f}")
    c2.metric("52-Week High P/E", f"{hist_pe.tail(252).max():.2f}")
    c3.metric("Historical Median", f"{hist_pe.median():.2f}")

    # --- GRAPH 1: TIME SERIES TREND WITH ROLLING MEAN ---
    st.subheader("1. Valuation Trend & Mean Reversion")
    data['MA_200'] = data['Proxy_PE'].rolling(window=200).mean() # 200-day moving average

    fig1 = px.line(data, y=['Proxy_PE', 'MA_200'],
                  labels={'value': 'P/E Ratio', 'Date': 'Year'},
                  title="P/E Ratio vs. 200-Day Moving Average",
                  color_discrete_map={"Proxy_PE": "#636EFA", "MA_200": "#EF553B"})
    st.plotly_chart(fig1, use_container_width=True)

    # --- GRAPH 2 & 3: DISTRIBUTION & OUTLIERS ---
    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("2. Distribution Density")
        fig2 = px.histogram(data, x="Proxy_PE", nbins=50, marginal="rug",
                           title="How Often Does This P/E Occur?")
        fig2.add_vline(x=current_pe, line_color="red", line_dash="dash", annotation_text="Current")
        st.plotly_chart(fig2, use_container_width=True)

    with col_right:
        st.subheader("3. Statistical Outliers")
        fig3 = px.box(data, y="Proxy_PE", points="all",
                     title="P/E Range & Quartiles")
        st.plotly_chart(fig3, use_container_width=True)

    # --- GRAPH 4: CORRELATION (Price vs Earnings) ---
    st.subheader("4. Fundamental Correlation (Log Scale)")
    fig4 = px.scatter(data, x="Close", y="Proxy_PE", trendline="ols",
                     title="Does Price Growth Outpace Valuation?",
                     labels={"Close": "Stock Price", "Proxy_PE": "Valuation Multiple"})
    st.plotly_chart(fig4, use_container_width=True)

else:
    st.error("Ticker not found. Please try a standard symbol like MSFT or GOOGL.")